// AUTO-GENERATED by scripts/cutout-pipeline/process_cutout.py — do not edit.
// Run the pipeline to regenerate.
export type CutoutEntry = { comName: string; w: number; h: number; mask: number[][] };
export type CutoutManifest = Record<string, CutoutEntry>;
export const CUTOUTS: CutoutManifest = {
  "accipiter-cooperii": {
    "comName": "Cooper's Hawk",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "actitis-macularius": {
    "comName": "Spotted Sandpiper",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "aix-sponsa": {
    "comName": "Wood Duck",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "anas-platyrhynchos": {
    "comName": "Mallard",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "archilochus-colubris": {
    "comName": "Ruby-throated Hummingbird",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "baeolophus-bicolor": {
    "comName": "Tufted Titmouse",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "bombycilla-cedrorum": {
    "comName": "Cedar Waxwing",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "branta-canadensis": {
    "comName": "Canada Goose",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "buteo-jamaicensis": {
    "comName": "Red-tailed Hawk",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "cardinalis-cardinalis": {
    "comName": "Northern Cardinal",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "chaetura-pelagica": {
    "comName": "Chimney Swift",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "coccyzus-americanus": {
    "comName": "Yellow-billed Cuckoo",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "colaptes-auratus": {
    "comName": "Northern Flicker",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "columba-livia": {
    "comName": "Rock Pigeon",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "contopus-virens": {
    "comName": "Eastern Wood-Pewee",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "corvus-brachyrhynchos": {
    "comName": "American Crow",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "corvus-ossifragus": {
    "comName": "Fish Crow",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "cyanocitta-cristata": {
    "comName": "Blue Jay",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "dryobates-pubescens": {
    "comName": "Downy Woodpecker",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "dryobates-villosus": {
    "comName": "Hairy Woodpecker",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "dryocopus-pileatus": {
    "comName": "Pileated Woodpecker",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "dumetella-carolinensis": {
    "comName": "Gray Catbird",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "empidonax-virescens": {
    "comName": "Acadian Flycatcher",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "falco-sparverius": {
    "comName": "American Kestrel",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "haemorhous-mexicanus": {
    "comName": "House Finch",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "haliaeetus-leucocephalus": {
    "comName": "Bald Eagle",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "hirundo-rustica": {
    "comName": "Barn Swallow",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "icterus-spurius": {
    "comName": "Orchard Oriole",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "megaceryle-alcyon": {
    "comName": "Belted Kingfisher",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "melanerpes-carolinus": {
    "comName": "Red-bellied Woodpecker",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "melanerpes-erythrocephalus": {
    "comName": "Red-headed Woodpecker",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "meleagris-gallopavo": {
    "comName": "Wild Turkey",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "melospiza-melodia": {
    "comName": "Song Sparrow",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "mimus-polyglottos": {
    "comName": "Northern Mockingbird",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "molothrus-ater": {
    "comName": "Brown-headed Cowbird",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "myiarchus-crinitus": {
    "comName": "Great Crested Flycatcher",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "pandion-haliaetus": {
    "comName": "Osprey",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "passer-domesticus": {
    "comName": "House Sparrow",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "passerina-caerulea": {
    "comName": "Blue Grosbeak",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "petrochelidon-pyrrhonota": {
    "comName": "Cliff Swallow",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "pheucticus-ludovicianus": {
    "comName": "Rose-breasted Grosbeak",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "piranga-rubra": {
    "comName": "Summer Tanager",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "poecile-atricapillus": {
    "comName": "Black-capped Chickadee",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "poecile-carolinensis": {
    "comName": "Carolina Chickadee",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "polioptila-caerulea": {
    "comName": "Blue-gray Gnatcatcher",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "progne-subis": {
    "comName": "Purple Martin",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "quiscalus-quiscula": {
    "comName": "Common Grackle",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "regulus-satrapa": {
    "comName": "Golden-crowned Kinglet",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "seiurus-aurocapilla": {
    "comName": "Ovenbird",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "sialia-sialis": {
    "comName": "Eastern Bluebird",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "sitta-carolinensis": {
    "comName": "White-breasted Nuthatch",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "sphyrapicus-varius": {
    "comName": "Yellow-bellied Sapsucker",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "spinus-tristis": {
    "comName": "American Goldfinch",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "spizella-passerina": {
    "comName": "Chipping Sparrow",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "spizella-pusilla": {
    "comName": "Field Sparrow",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "stelgidopteryx-serripennis": {
    "comName": "Northern Rough-winged Swallow",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "streptopelia-decaocto": {
    "comName": "Eurasian Collared-Dove",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "sturnella-magna": {
    "comName": "Eastern Meadowlark",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "sturnus-vulgaris": {
    "comName": "European Starling",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "tachycineta-bicolor": {
    "comName": "Tree Swallow",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "thryothorus-ludovicianus": {
    "comName": "Carolina Wren",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "toxostoma-rufum": {
    "comName": "Brown Thrasher",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "tringa-flavipes": {
    "comName": "Lesser Yellowlegs",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "tringa-solitaria": {
    "comName": "Solitary Sandpiper",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "troglodytes-aedon": {
    "comName": "House Wren",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "turdus-migratorius": {
    "comName": "American Robin",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "tyrannus-tyrannus": {
    "comName": "Eastern Kingbird",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "vireo-flavifrons": {
    "comName": "Yellow-throated Vireo",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "vireo-gilvus": {
    "comName": "Warbling Vireo",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "zenaida-macroura": {
    "comName": "Mourning Dove",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "zonotrichia-albicollis": {
    "comName": "White-throated Sparrow",
    "w": 800,
    "h": 600,
    "mask": []
  },
  "sitta-canadensis": {
    "comName": "Red-breasted Nuthatch",
    "w": 800,
    "h": 600,
    "mask": []
  }
};
