#!/usr/bin/env python3
"""
Cutout pipeline for the BirdNET-Pi public site.

Takes a raw illustration (from Nano Banana — illustration on solid background)
and produces:
  1. apps/web/public/birds/<slug>.png  — tight transparent PNG, long-edge ≤ 560px
  2. apps/web/lib/cutouts.generated.ts  — DIMS + low-res binary masks for the
     spiral-pack collage layout

Usage:
  process_cutout.py --raw path/to/raw.jpg \
                    --slug cardinalis-cardinalis \
                    --com-name "Northern Cardinal" \
                    --web-dir apps/web

Slug convention: scientific name, lowercased, spaces→hyphens
  e.g. "Cardinalis cardinalis" -> "cardinalis-cardinalis"
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from PIL import Image
from rembg import remove

MAX_LONG_EDGE = 560        # match the reference site's DIMS scale
MASK_GRID = 28             # low-res binary mask resolution (NxN); reference ~30
MASK_ALPHA_THRESHOLD = 32  # alpha >= this becomes 1 in the mask
DILATE = 1                 # mask dilation (in low-res cells) — bakes in the visual gap


def cutout_and_crop(raw_path: Path) -> Image.Image:
    """Run rembg, crop tight to alpha bbox, return RGBA Image."""
    src = Image.open(raw_path)
    out = remove(src)  # returns RGBA
    bbox = out.getbbox()
    if bbox is None:
        raise RuntimeError(f"rembg produced empty image for {raw_path}")
    return out.crop(bbox)


def fit_to_long_edge(im: Image.Image, max_edge: int) -> Image.Image:
    w, h = im.size
    long_edge = max(w, h)
    if long_edge <= max_edge:
        return im
    scale = max_edge / long_edge
    new_size = (round(w * scale), round(h * scale))
    return im.resize(new_size, Image.LANCZOS)


def build_mask(im: Image.Image, grid: int, threshold: int, dilate: int) -> list[list[int]]:
    """Downsample alpha channel to grid×grid binary mask, then dilate."""
    # Resize alpha to match aspect ratio inside grid×grid
    w, h = im.size
    long_edge = max(w, h)
    mw = max(1, round(w / long_edge * grid))
    mh = max(1, round(h / long_edge * grid))
    alpha = im.getchannel("A").resize((mw, mh), Image.LANCZOS)
    raw = [
        [1 if alpha.getpixel((x, y)) >= threshold else 0 for x in range(mw)]
        for y in range(mh)
    ]
    if dilate <= 0:
        return raw
    # Square-kernel dilation
    out = [[0] * mw for _ in range(mh)]
    for y in range(mh):
        for x in range(mw):
            if raw[y][x]:
                for dy in range(-dilate, dilate + 1):
                    for dx in range(-dilate, dilate + 1):
                        ny, nx = y + dy, x + dx
                        if 0 <= ny < mh and 0 <= nx < mw:
                            out[ny][nx] = 1
    return out


def update_manifest(manifest_path: Path, slug: str, com_name: str, dims: tuple[int, int], mask: list[list[int]]):
    """Read/merge/write JSON manifest. Keeps things idempotent."""
    data = {}
    if manifest_path.exists():
        data = json.loads(manifest_path.read_text())
    data[slug] = {
        "comName": com_name,
        "w": dims[0],
        "h": dims[1],
        "mask": mask,
    }
    manifest_path.write_text(json.dumps(data, indent=2, sort_keys=True))


def emit_ts(manifest_path: Path, ts_path: Path):
    """Emit a TS module the Next.js app imports."""
    data = json.loads(manifest_path.read_text())
    ts_path.write_text(
        "// AUTO-GENERATED by scripts/cutout-pipeline/process_cutout.py — do not edit.\n"
        "// Run the pipeline to regenerate.\n"
        "export type CutoutEntry = { comName: string; w: number; h: number; mask: number[][] };\n"
        "export type CutoutManifest = Record<string, CutoutEntry>;\n"
        f"export const CUTOUTS: CutoutManifest = {json.dumps(data, indent=2, sort_keys=True)};\n"
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--raw", required=True, type=Path, help="raw illustration (jpg/png)")
    ap.add_argument("--slug", required=True, help="scientific-name-hyphenated, lowercase")
    ap.add_argument("--com-name", required=True, help="common name, e.g. 'Northern Cardinal'")
    ap.add_argument("--web-dir", required=True, type=Path, help="apps/web root")
    args = ap.parse_args()

    web_dir: Path = args.web_dir.resolve()
    out_dir = web_dir / "public" / "birds"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_png = out_dir / f"{args.slug}.png"
    manifest = web_dir / "lib" / "cutouts.manifest.json"
    ts_out = web_dir / "lib" / "cutouts.generated.ts"
    manifest.parent.mkdir(parents=True, exist_ok=True)

    print(f"[1/4] rembg + tight-crop: {args.raw.name}")
    im = cutout_and_crop(args.raw)

    print(f"[2/4] resize to long-edge {MAX_LONG_EDGE}px (was {im.size})")
    im = fit_to_long_edge(im, MAX_LONG_EDGE)
    print(f"      -> {im.size}")
    im.save(out_png, optimize=True)
    print(f"      wrote {out_png}")

    print(f"[3/4] build {MASK_GRID}-grid mask (dilate={DILATE})")
    mask = build_mask(im, MASK_GRID, MASK_ALPHA_THRESHOLD, DILATE)
    filled = sum(sum(row) for row in mask)
    print(f"      mask {len(mask[0])}x{len(mask)}, filled cells: {filled}")

    print(f"[4/4] update manifest + emit TS")
    update_manifest(manifest, args.slug, args.com_name, im.size, mask)
    emit_ts(manifest, ts_out)
    print(f"      wrote {manifest.name} + {ts_out.name}")

    print("done.")


if __name__ == "__main__":
    main()
